@CSharpTest_HostAddress = http://localhost:5163

POST {{CSharpTest_HostAddress}}/employees/add
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "name": "John Doe",
  "department": "Management",
  "salary": 100000
}

###

GET {{CSharpTest_HostAddress}}/employees

###